### ISSUE TITLE
Presentaciones

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#1]
Hola!

Usemos este espacio para conocernos un poco más... :-)

Recordad que estos [_issues_](https://github.com/Fictizia/Curso-JS-Avanzado-para-desarrolladores-Front-end_ed2/issues) nos permiten abrir y participar en debates, compartir recursos, plantear preguntas y muchas cosas más! 

Podemos usar [Markdown](https://guides.github.com/features/mastering-markdown/) para salirnos del texto plano y enriquecer nuestras aportaciones.

**Comment by KoolTheba** [comment]
Holiiii!! 

Please uniros a Slack que tenemos un canal solo para nosotr@s 😎

**Comment by UlisesGascon** [comment]
@Fa-v tienes que aceptar al invitación en https://github.com/Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3/invitations o en el email ;-)

**Comment by Fa-v** [comment]
Me dice esto: 

> Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account.

**Comment by karinagdavila** [comment]
Hola a todos!
No hay link para el canal de slack @KoolTheba :(((

**Comment by JGuijarro** [comment]
**Hola gente**, no entiendo lo de crear un Gist, me pide que ponga una URL y no se de donde sacarla :'(

Esto es lo que quería poner en mi Gist, lo dejo aquí para luego xD

[index.html.txt](https://github.com/Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3/files/2450971/index.html.txt)

**Comment by GuillermoBaldan** [comment]
Bueno, qué es esto? ¿Esto no va de presentarse?
Pues yo soy uno que quiere montar una empresa porque piensa que el mejor modo de mejorar el mundo es a través de los negocios cuyo fin no es el dinero. 
Yo programo, además de porque me gusta, porque entiendo que puedo generar riqueza con mi trabajo. Para mí la riqueza tiene que ver con muchas más cosas a parte de dinero como:
-estabilidad
-conocimiento
-empleo
-bienestar 
-propósito
¿Qué mas puedo decir de mí?
Me gusta el deporte aunque no salgo a correr todos los días.
Me gusta mucho, mucho las bandas sonoras y la llamada "música épica" 
Creo que la realidad supera la ficción y que la Verdad nos hace libres.
Me gusta mucho conocer gente y me paso la vida haciendo nuevos amigos porque he descubierto que círculos amplios de amistades están relacionados con un buen nivel de salud social.
Hay quien me considera un fanático de los mapas mentales, me encantan esos diagramas y tengo más de 1000 de ellos en mi ordenador.
Toda mi vida he tenido una intensa sensación de que había nacido con un propósito, aunque llegué a pensar que eso era una alucinación mental de mi cerebro, desde hace un año he trabajado a nivel personal sobre ello y he estado persiguiendo ese propósito.
Una de mis mayores motivaciones es dejar un legado, creo que lo que nos hace estar vivos realmente no es no son las funciones metabólicas de nuestros organismos, no son las funciones sociales que desempeñamos ni las actividades que realizamos ni siquiera aquellas que nos apasionan. Lo que nos hace estar vivos realmente y nos da vida ni siquiera tiene que ver con nuestra capacidad de resolver puzzles científicos o de ingeniería sino que tiene que ver con nuestra capacidad de amar. Ser recíproco no tiene porque implicar amor necesariamente más el perdón permite que el amor salga y el hacer el bien a nuestros enemigos hace que el amor brille.
En el universo hay una relación entre la masa y la energía que viene dada en la famosa ecuación de Einstein, E=mc^2. También hay una relación entre el Amor y la Verdad. Y es que no creo que haya una Verdad sin Amor.
Creo que la Esperanza nos empuja hasta la Verdad y no creo en la existencia de Amor sin compromiso. Yo estoy comprometido con mis paisanos de Móstoles, con mis paisanos de la Comunidad de Madrid, con los de los pueblos de la península ibérica y con el resto de paisanos del planeta y entre otras cosas por esa razón programo y voy a osw y quiero montar una empresa. Amo al mundo y me comprometo por enriquecerlo.

**Comment by qlchose** [comment]
# Hola!

## Mi nombre es Eva

### Estoy aquí para aprender


mi experiencia  | en programación? 
----------------------------------------- | -----------------------------

[X]es bastante pobre 
[ ] se limita a scripting bash,


#### y a la automatización  de `<procesos>` .
 
*Esto* junto **con el soporte** conforman mi >experiencia,

 * dentro del marco IT,

 * He trabajado, 
	* en soporte para Gestión de Identitades, 
	* helpdesk, para ***incidencias de usuarios***
 
 1. también tengo algo de experiencia en gestión de calidad; 
 1. dentro de la parte de documentación técnica
		| ciclo | de vida | del documento |
		| :-----| :------: | ------: |
		| mejora | de | procesos |
		
[Con titulo](http://joedicastro.com "link sintaxis Markdown")

<http://joedicastro.com>
