### ISSUE TITLE
Curso Chrome Developers que no sea de Pluralsight

### ISSUE THREAD

**Issue by qlchose** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#10]
Ya consumí el periodo de prueba gratuito

Saludos¡¡

**Comment by GuillermoBaldan** [comment]
A ver...no me enterao de que va esto.

**Comment by qlchose** [comment]
> A ver...no me enterao de que va esto.

Es para la clase de hoy, uno de los recursos. Es un curso de Google Chrome Developers, pero como ya consumí el período de prueba. Es por eso, por si hubiera otro

Aprovecho, tenemos incidencia en el trabajo y me voy a retrasar hoy. Disculpadme.
