### ISSUE TITLE
FictiziaAnswers

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#108]
Guillermo: Ulises, ¿Porqué no habéis hecho un foro donde los alumnos y ex-alumnos publiquen su preguntas y se ayuden unos a otros?
Ulises: hmmm...stackoverflow?
Guillermo (empezando a entusiasmarse): Pero en stackoverflow son super bordes enseguida te votan paa abajo y te marcan como "duplicate", además no tienen las etiquetas molonas que tenemos nosotros como "Inquietud Existencial ", "Cosas que programar antes de morir" y en breve "ÑapaScript"(Identica el mal y superalo con "SeniorScript" y "SeniorScript++"). Además imagina las posibilidades de marketing y además es una forma de que fictizia siga haciendo comunidad, venga tio! nunca se tienen suficientes alumnos ...además Yo sueño con algo mejor que stackoverflow (Guillermo en modo soñador)...un sitio que relacione las preguntas con los proyectos ¡Es el futuro! (Guillermo en modo visionario...). Venga Ulises, que me marco un proyecto...(Guillermo viniendose arriba....)
Ulises: En breve vienen los reyes magos y aún me debes la máquina expendedora...

**Comment by UlisesGascon** [comment]
### ... y aún me debes la máquina expendedora... hahahaha
![Meme](https://media.giphy.com/media/IMSq59ySKydYQ/giphy.gif)
