### ISSUE TITLE
¿Por qué no hemos visto clases en javascript?

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#109]
Hecho de menos las clases de python...
Supongo que no son necesarias en javascript...no?

**Comment by UlisesGascon** [comment]
En principio... empezaremos a tocar el paradigma de POO esta semana. Justo antes de irnos de vacaciones navideñas 👍
