### ISSUE TITLE
¿Qué son los métodos?

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#111]
No me queda claro en los apuntes de clase.
Me pregunto acerca de cuando hay que usarlo y que similitudes y diferencias presentan con respecto a las funciones.

**Comment by UlisesGascon** [comment]
Respuesta corta: Los métodos simplemente son propiedades de `typeof function` en un objeto con algunos cambios interesantes. 
Respuesta Larga: [Method vs Functions, and other questions
](https://stackoverflow.com/a/15285702)

De todas formas lo vemos esta tarde en clase ^^
