### ISSUE TITLE
[Oportunidad] ¡Salvemos Memezinga!

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#116]
![duat_i_x4amprob](https://user-images.githubusercontent.com/5110813/50217282-8f87fb80-0388-11e9-96df-c44f66217276.jpg)

**Si tienes tiempo y ganas... ¡es tu oportunidad!**

### Idea
- [ ] Tirar todo y empezar de cero
- [ ] Ya que somos Guilders del Guild24... va siendo hora de tomar cartas en algunos proyectos ^^
- [ ] ¡Superemos al equipo del año pasado!
- [ ] Trabajo intenso en modo Agile con Code Reviews entre nostor@s y GitFlow
- [ ] Intentaremos simular un entorno de trabajo real con fechas de entrega y estimaciones. 
- [ ] Trabajaremos por parejas
- [ ] Haremos reuniones fuera de clase para coordinar
- [ ] Implementar nuevas funcionalidades usando "potencialmente" Firebase

### Básico
- [Somos @awesomemzg en Twitter](https://twitter.com/awesomemzg)
- [memezinga.com](http://memezinga.osweekends.com/)

**Comment by GuillermoBaldan** [comment]
Hey! Un momento! Tirar todo lo logrado hasta ahora!!??
![mis memes celebres_6967869519199465425](https://user-images.githubusercontent.com/43887483/50235031-48652f00-03b7-11e9-87b1-bf8a312d3078.jpeg)
![mis memes celebres_56884323623536037](https://user-images.githubusercontent.com/43887483/50235651-ab0afa80-03b8-11e9-9244-09ec6d786e6c.jpeg)
![mis memes celebres_8044563483691805863](https://user-images.githubusercontent.com/43887483/50236180-0be70280-03ba-11e9-8f8d-c0e4a7ba9594.jpeg)
![mis memes celebres_8109750825975548042](https://user-images.githubusercontent.com/43887483/50236191-13a6a700-03ba-11e9-8a29-bc0fb27ac142.jpeg)
