### ISSUE TITLE
Monetizando Memetinga

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#119]
¿Hay algo mejor que programar tú?
Siiiiiii!!!!
Qué además programen otros para ti...
Os imagináis...??
![mis memes celebres_5220745652608951673](https://user-images.githubusercontent.com/43887483/50238042-b103da00-03be-11e9-8c43-4e719e3de2ed.jpeg)
Yo soy de los que creen que el mejor software no solo se hace con voluntarios...
![mis memes celebres_8879158173503950254](https://user-images.githubusercontent.com/43887483/50238144-ead4e080-03be-11e9-8636-99fe943c2f8b.jpeg)

**Comment by GuillermoBaldan** [comment]
Propongo Monetizar la API

Supongo que sobra decir que aunque nunca llegue a recibir un euro es para mí un privilegio poder participar en este proyecto.

**Comment by UlisesGascon** [comment]
No se puede monetizar... los proyectos de OSW son todos sin animo de lucro ;-)
