### ISSUE TITLE
Generando números aleatorios entre 0 (incluido) y 1 (incluido)

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#12]
Es bien sabido que la función Math.random() genera números aleatorios entre 0 (incluido) y 1 (excluido).
¿Alguien sabe alguna forma de conseguir una función a partir de Math.random() que me genere números aleatorios entre 0 (incluido) y 1 (incluido)

**Comment by UlisesGascon** [comment]
Este sería un [ejemplo clásico](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Math/random) usar esto, pero necesitarías afinar un poco [la fórmula](https://stackoverflow.com/a/1527820)

```javascript
/**
 * Returns a random integer between min (inclusive) and max (inclusive)
 * Using Math.round() will give you a non-uniform distribution!
 */
function getRandomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

getRandomInt(0, 1) 
```

**Comment by GuillermoBaldan** [comment]
No me gusta que la distribución generada no sea uniforme. A primera vista me veo tentado a decir que este problema parece computacionalmente imposible de resolver.
