### ISSUE TITLE
Reto: Hack The Box

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#121]
### ¡Únete a Hack The Box](https://www.hackthebox.eu/invite) !

![screen-shot-2017-11-22-at-2 22 39-pm](https://user-images.githubusercontent.com/5110813/48711759-52efa580-ec0c-11e8-80e6-468101b8e14b.png)

¿Lo has logrado?

**:warning: No compartas como lo lograste**
> La primera regla de Hack The Box: Nadie habla sobre cómo registrarse en Hack The Box.

**Comment by Fa-v** [comment]
I'm in!
![pig-dancing](https://media.giphy.com/media/l4JyKJatpJ78vC1kA/giphy.gif)

**Comment by UlisesGascon** [comment]
Bravo @Fa-v !!
