### ISSUE TITLE
¿Cómo generar un array de objetos dinámicamente?

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#13]
Se puede mirar una introducción a esta cuestión en un issue planteado anteriormente, creo que podría ayudar a enteder este issue aunque creo que este se puede entender por si mismo:
[¿Cómo me monto un array de objetos?](https://github.com/Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3/issues/11)
Queremos generar dinámicamente un array de objetos que contengan dos propiedades o atributos llamados:
- **coursename**: guarda el nombre del curso
- **progress**: guarda el progreso en el curso

El nombre del array de objetos es **usercourses**.
Yo había pensado lo siguiente:
```
for (i=0;i<numberofcourses;i++){
    usercourses[i] = new Object();
    usercourses[i].coursename = listofcourses[Math.floor(Math.random()*listofcourses.length)];
    usercourses[i].progress = Math.floor(Math.random()*100);
        }
```
- donde `listofcourses` es una lista de cursos y la expresión:
`listofcourses[Math.floor(Math.random()*listofcourses.length)];`
lo que hace es retornar un curso de forma aleatoria de la lista de cursos.
- donde `numberofcourses` es un número aleatorio que depende de la longitud de `listofcourses`.

**El problema**
La consola me arroja un error:

> Uncaught TypeError: Cannot set property 'progress' of undefined

dándome el fallo en la siguiente línea de código:
`usercourses[i].progress = Math.floor(Math.random()*100);`

**Comment by UlisesGascon** [comment]
@GuillermoBaldan lo más fácil para pensar en estructuras de datos es hacer uso de algún sistema como [json-generator](https://www.json-generator.com/). Es más sencillo partir de este punto.


### Un array de objetos...

```javascript
var listaCursos = [{
		titulo: "Mecanica avanzada I",
		ref: "0001",
		tipo: "online"
	}, {
		titulo: "Mecanica de fuidos IV",
		ref: "0023",
		tipo: "presencial"
	}]
```

Mañana lo vemos si quieres en clase.... en principio en unas pocas clases ya estaremos viendo estructuras de datos ;-)

**Comment by GuillermoBaldan** [comment]
A ver...
En principio me vale esto, que[ lo saqué de esta pregunta que publiqué en stackoverflow](https://es.stackoverflow.com/questions/203033/crear-un-array-de-objetos-din%C3%A1micamente-en-javascript/203051#203051):
```
var usercourses = [] //Aquí cambié la expresión var usercourses = new Object();
var listofcourses = ['matemáticas', 'geografía', 'física', 'biología', 'filosofía'];
var numberofcourses = Math.floor(Math.random()*listofcourses.length);
for (i = 0; i < numberofcourses; i++) {
  usercourses[i] = new Object();
  usercourses[i].coursename = listofcourses[Math.floor(Math.random() * listofcourses.length)];
  usercourses[i].progress = Math.floor(Math.random() * 100);
}

for (var c in usercourses) {
  console.log(c, usercourses[c]);
}
```
Lo pegué en mi programa y me funciona

¿Qué opinas Ulises?

**Comment by UlisesGascon** [comment]
No pinta mal estructura, pero tendríamos que ver como escalaría cuando tengas muchos cursos y alumn@s ;-)

**Comment by GuillermoBaldan** [comment]
Bueno, eso creo que sería otro issue. Voy a cerrar este.
