### ISSUE TITLE
No me genera página web el Cloud9

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#14]
Me sale el siguiente mensaje:
> Cloud9 can't get you to your requested workspace. Here are some suggestions on how to figure out what's going on:
> Check that the workspace name (microcourses_app) and username (guillermobaldan) are typed correctly.
> Check that the server is successfully running on Cloud9:
> If the server hit an error, the output window will have a message telling you what it is
> If you're in the middle of debugging code, your server might be paused right now
> The server might be running on a different port; make sure it's on port $PORT with $IP as the IP address

¿Alguien tiene idea de cómo se puede solucionar?

**Comment by UlisesGascon** [comment]
Estás usando Apache o Node?
