### ISSUE TITLE
FPGA

### ISSUE THREAD

**Issue by JGuijarro** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#146]
https://planetachatbot.com/qu%C3%A9-es-una-fpga-y-por-qu%C3%A9-jugar%C3%A1n-un-papel-clave-en-el-futuro-e76667dbce3e

**Comment by GuillermoBaldan** [comment]
He dejado un comentario:
Yo he empleado, FPGAs de Xilinx para implementar sistemas de SFD (Software Define Radio). Estas técnologías combinadas permiten fabricar un sistema de telecomunicaciones universal capaz de recibir y transmitir cualquier tipo de señal radioeléctrica.
