### ISSUE TITLE
Parece que la variable i es cambiada de valor desde dos for

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#16]
Sea este el código:

```javascript
//Variables globales
var listofcourses = ["Electrónica Digital I", "Electrónica Digital II", "Teoría de circuitos", "Ecuaciones Diferenciales I", "Ecuaciones Diferenciales II", "Ecuaciones Diferenciales III", "Mecánica de fluidos I", "Mecánica de fluidos II", "Mecánica de fluidos IV", "Proyecto red social", "Proyecto Whatsapp", "Proyecto Criptomoneda", "Proyecto Entorno de Trabajo Colaborativo", "Diseño de cohetes I", "Diseño de cohetes II", "Diseño de cohetes III", "Diseño de alas", "Diseño de hélices", "Proyecto Diseño y Construcción de un ala de avión", "Proyecto: Construcción de un pequeño helicóptero", "diseño de drones", "Proyecto: Construcción de una máquina herramienta", "Proyecto: Construcción de una impresora 3D", "Sensores I", "Sensores II", "Sensores III"];
var NumberOfIdCourseFigures = 10;
var maxage = 55;
var minage = 12;
//Funciones
function generateIdCourse(numberoffigures) {
    var IdChain = "";
    for (j = 0; j < numberoffigures; j++) {
        IdChain = IdChain + String(Math.floor(Math.random() * 10));
        console.log(IdChain);
        console.log("j es:" + j + " numberoffigures es:" + numberoffigures);
    }
    return IdChain;
}

function RandomData() {
    //Asignación de variables
    var name = document.querySelector("#Name");
    var email = document.querySelector("#Email");
    var username = document.querySelector("#Username");
    var password = document.querySelector("#Password");
    var ip = document.querySelector("#Ip");
    var country = document.querySelector("#Country");
    var age = document.querySelector("#Age");
    var photo = document.querySelector("#Photo");
    var courses = document.querySelector("#courses");
    var numberofcourses = Math.floor(Math.random() * listofcourses.length);
    var usercourses = new Object();

    //Asignación de campos
    name.innerHTML = faker.name.findName();
    email.innerHTML = faker.internet.email();
    username.innerHTML = faker.internet.userName();
    password.innerHTML = faker.internet.password();
    ip.innerHTML = faker.internet.ip();
    country.innerHTML = faker.address.country();
    age.innerHTML = Math.floor(Math.random() * (maxage - minage)) + minage; //Las edades de los usuarios están entorno a minage y maxage

    var usercourses = [];
    for (i = 0; i < numberofcourses; i++) {
        usercourses[i] = new Object();
        usercourses[i].coursename = listofcourses[Math.floor(Math.random() * listofcourses.length)];
        usercourses[i].progress = Math.floor(Math.random() * 100);
        usercourses[i].Id = generateIdCourse(NumberOfIdCourseFigures);


    }

}
```
Dentro de la función `RandomData` hay un for y dentro se llama a la función `generateIdCourse`, ahora he cambiado la variable contador del for que hay dentro de `generateIdCourse `porque he observado que cuando la variable era i para ambos for, la función `generateIdCourse `caía en bucle infinito o casi. Al cambiar la i por j en el for de la función `generateIdCourse `ya no se me cae en bucle. Yo pensaba que dentro de la memoria de programa se creaban dos variables i distintas una que operaba dentro del for que esta dentro de la función `RandomData `y otra para el for que está dentro de `generateIdCourse`, pero parece que estaba equivocado.
¿Qué opinais?

**Comment by UlisesGascon** [comment]
sip... tiene todo el sentido @GuillermoBaldan.

Por un lado siempre que definas una variable debes hacerlo con `var`, `let` o `const`, eso debería de ayudarte a solventar muchos problemas de Scope, al margen que es una muy mala práctica no definir.

Por otro lado en JavaScript existe un tema de `scope` que veremos más adelante donde puedes sufrir comportamientos "inesperados"

### Para ir adelantando...
- [Should You Truly Never Use var?](https://dev.to/johnwolfe820/should-you-never-truly-use-var-bdi)
- [Why You Shouldn’t Use ‘var’ Anymore](https://hackernoon.com/why-you-shouldnt-use-var-anymore-f109a58b9b70)
- [Entendiendo scopes de variables en JavaScript](https://yeisondaza.com/entendiendo-scopes-de-variables-en-javascript)
- [MDN | Scope](https://developer.mozilla.org/en-US/docs/Glossary/Scope)
- [Concepto de scope en JavaScript](http://www.enrique7mc.com/2015/12/concepto-de-scope-en-javascript/)
