### ISSUE TITLE
Plataformas para hacer pagos para donaciones en ONGs

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#163]
Estaba pensando en poner pay pal para web de la ONG que estoy haciendo. Pero me dicen que tiene unos costes fijos de 30 euros al año.
¿Que opciones tengo?

**Comment by UlisesGascon** [comment]
Todo el mundo querrá llevarse una comisión por el riesgo que asumen y el trabajo de mantener y desarrollar su software. Por lo general tienes muchas cosas previas que incluir como el soporte a HTTPS
