### ISSUE TITLE
Patrón de diseño para hacer pagos a causas para proyecto web de ONG

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#164]
Quiero ver como programar un sistema de pagos en una web de una ONG, en la que el cliente pueda seleccionar una causa X de una serie de causas para hacer una donación puntual.
Al final no se puede tener una cuenta de banco para cada causa, porque es un sobrecoste, entonces solo hay una única cuenta de banco para toda la ONG. Pero la web de la ONG registra a que causa se ha donado el dinero para mostrar el progreso de la campaña de financiación de dicha a causa a todos los visitantes de la web, algo así como las campañas de financiación que podemos en webs como la de kickstarter.
¿Alguna idea?

**Comment by UlisesGascon** [comment]
Lo vemos esta tarde en clase ^^
