### ISSUE TITLE
Modelo de datos para la app del Guild Ideas

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#166]
![Guild Ideas Data Model-2 ](https://user-images.githubusercontent.com/43887483/58577931-e521d780-8247-11e9-8262-01ef893b6550.jpeg)

**Comment by UlisesGascon** [comment]
Lo vemos hoy en clase si quieres :-)
