### ISSUE TITLE
Comportamiento inesperado midiendo tiempos de ejecución

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#17]
Hola estoy haciendo el ejercicio 4 de la sesión 4 del máster:

> 4 - Agrupa cada tipo de mensaje y añade un contador de tiempo por cada grupo.

```
var start_log = Date.now();
console.log("Guillermo");
var end_log = Date.now();

var start_info = Date.now();
console.info("Guillermo");
var end_info = Date.now();

var start_warn = Date.now();
console.warn("Guillermo");
var end_warn = Date.now();

console.log("El tiempo empleado en mostrar mi nombre usando console.log es: "+(end_log-start_log));
console.info("El tiempo empleado en mostrar mi nombre usando console.info es: "+(end_info-start_info));
console.warn("El tiempo empleado en mostrar mi nombre usando console.warn es: "+(end_warn-start_warn));
```
Creo que hay un problema porque me arroja unos tiempos de ejecución de 11 para console.log y de 0 y 0 para console.info y console.warn respectivamente.

¿Qué opinaís?

**Comment by UlisesGascon** [comment]
Yo incluso llego al 0 en todo... Es raro pero creo que tiene sentido, ya que no es mucho tiempo el necesario para hacer un `console.log`, etc..
