### ISSUE TITLE
Trabajando en Cloud9. Error 404

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#18]
Tengo un worspace público de Cloud9 para hacer ejercicios y pruebas en:
`https://ide.c9.io/guillermobaldan/example`

Mi código en html:
```
<!DOCTYPE html>
<lang="en">
    <head>
        <title>
            Session 4 Exercise 5
        </title>
        <link rel="stylesheet" href="https://ide.c9.io/guillermobaldan/example/css/S4E5style.css">
        <script src="https://ide.c9.io/guillermobaldan/example/js/Exercises Session 4/S4E5.js"></script>
        <meta charset="utf-8"/>
        <div><h1 id="NameTitle">Name</h1>
    </head>
    <body>
        
    </body>

```
**El problema**
Cuando trato de cargar la página web del código html anterior me dan dos errores 404 en el navegador chrome:

> GET https://ide.c9.io/guillermobaldan/example/css/S4E5style.css net::ERR_ABORTED 404 (Not Found)
> 2E5.html:8 
> GET https://ide.c9.io/guillermobaldan/example/js/Exercises%20Session%204/S4E5.js net::ERR_ABORTED 404 (Not Found) 

¿Por qué me pasa esto si tengo los archivos .js y .css en las rutas correspondientes?

Os mando un pantallazo de mi entorno en Cloud9:
![s4e5_error404](https://user-images.githubusercontent.com/43887483/46747563-f070c480-ccb1-11e8-8a4c-8b6811ce3067.png)

**Comment by UlisesGascon** [comment]
Hola @GuillermoBaldan! Es normal este error... [C9.io tiene un proxy y unos mecanismos un poco complejos y no son tan obvios](https://community.c9.io/t/writing-a-simple-html-page/1726). 

Como consejo, intentaría evitar el uso de rutas absolutas como `https://ide.c9.io/guillermobaldan/example/css/S4E5style.css` y usaría rutas relativas como `../../css/S4E5style.css` o similares.

Por otro lado `https://ide.c9.io/guillermobaldan/example/...` es solo la URL de desarrollo, en C9 existe una URL especifica `https:/example-guillermobaldan.c9users.io/...` que es la que te permite ver el proyecto como una web. Si quieres mañana hago una demo en clase y te explico todo el manejo de rutas y puertos ;-)
