### ISSUE TITLE
Qué leer después de Javascript Inspírate

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#19]
Ya casi he terminado tu libro, Ulises.
Que libro me recomiendas que lea  ahora?
A mi me gustaría leer uno que te fuera desarrollando un proyecto o varios y te fuera explicando los conceptos en función de la necesidad de ese o esos proyectos.
Por cierto, tengo algún comentario de mejora. ¿Cómo te los hago llegar?

**Comment by UlisesGascon** [comment]
En principio te recomendaría estos tres (para el tramo del master actual):
- [Eloquent JavaScript (original en ingles)](https://www.amazon.com/Eloquent-JavaScript-3rd-Introduction-Programming/dp/1593279507/)
- [Eloquent Javscript en Español (incompleto)](http://hectorip.github.io/Eloquent-JavaScript-ES-online/)
- [You Don't Know JS (book series)](https://github.com/getify/You-Dont-Know-JS)
- [Secrets of the JavaScript Ninja](https://www.amazon.com/Secrets-JavaScript-Ninja-John-Resig/dp/193398869X)
- [JavaScript Ninja (traducción)](https://www.amazon.es/JavaScript-Ninja-Anaya-Multimedia-Manning/dp/8441533970)

Si quieres de los cambios y comentarios hablamos el lunes en clase y te cuento como hacer PRs al proyecto y demás ;-)
