### ISSUE TITLE
Hacktoberfest... soon!

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#2]
![hacktoberfest_2018_opengraph_1200x630](https://user-images.githubusercontent.com/5110813/46152256-ef32a700-c270-11e8-8511-387f876d8734.png)

**Comment by UlisesGascon** [comment]
@GuillermoBaldan -> https://hacktoberfest.digitalocean.com/stats/GuillermoBaldan

**Comment by JGuijarro** [comment]
Solicito una tutoría para tratar este tema. :computer:

**Comment by UlisesGascon** [comment]
### Pasos para @JGuijarro 

- Date de alta en [hacktoberfest](https://hacktoberfest.digitalocean.com/)
- Crear un repo en github para el proyecto personal (público)
- Crear una rama llamada `dev` -> `git checkout -b dev`
- Asegurarte que estas en la rama correcta

**bucle: repetir 5/6 veces**
- Trabajar el html de una vista del proyecto -> `camisetas.html`
- Comitear los cambios que haces en tu(s) fichero(s) -> `git commit -m "cambios en el diseño... bla,  bla..."`
- Pushear tus cambios a github. `git push origin dev`
- Pull Resquest de rama `dev` a `master` en tu propio repositorio, [doc](https://help.github.com/articles/about-pull-requests/)
- Aceptar la Pull Request, [doc](https://help.github.com/articles/merging-a-pull-request/)
