### ISSUE TITLE
Aprovechando la arquitectura hardware de los procesadores Intel Core i.X

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#21]
Me preguntaba si javascript aprovecha las arquitecturas multicore de los procesadores. Y si es así esperaría que javascript tuviera recursos a nivel de lenguaje para gestionar estos recursos computacionales.

**Comment by UlisesGascon** [comment]
En principio depende mucho del interprete que manejas, si estas haciendo frontend depende mucho del navegador donde se esta ejecutando tu JavaScript y sus capacidades respecto a la gestión de Hardware y recursos.

En el lado de Nodejs, la película cambia un poco, pero no es C/C++ en cualquier caso y se trabaja a muy alto nivel, lo que nos permite delegar en el interprete y progresar muy rápido el desarrollo de proyectos.
