### ISSUE TITLE
Ejercicio AJAX más sencillo posible

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#25]
Ya sé que es ir adelantado temario, pero siempre he pensado que lo mejor es aprender al propio ritmo.
¿Alguien sabe algún ejercicio sencillito tipo el "hola mundo" del AJAX?

**Comment by Fa-v** [comment]
Hola Guillermo, Free Code Camp tiene una introducción a [ajax APIs](https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax).
También está este artículo [guía básica sobre AJAX](https://developer.mozilla.org/es/docs/Web/Guide/AJAX/Primeros_Pasos) en MDN.
Espero que te sirvan :)
