### ISSUE TITLE
¿Por qué no está JQuery en el temario del curso?

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#26]
Ante todo confío en tu criterio, Ulises. Solo me gustaría saber tu opinión de Jquery. Supongo que en algún momento deberíamos aprenderlo, ¿no?

**Comment by UlisesGascon** [comment]
JQuery es una librería pontente para hacer manipulación del DOM y principalmente cuenta con miles de proyectos y plugins que la utilizan, lo que la convierte en una librería de referencia y una de las más veteranas de todo el ecosistema de JS. 

Pero no existe nada que no se pueda hacer con Jquery que no podamos hacer sin ella, ya que es todo JavaScript. 

Antes de IE11 todo era más complejo y tenías que tener muchas estrategias distintas para mantener una web compatible entre todos los navegadores... esto era una de las razones de peso más potentes para mantener proyectos con JQuery, pero hoy por hoy no es tan necesario para la mayoría de proyectos.

De todas formas con los conocimientos en JS y programación que tendrás en unas semanas no debería ser un problema enfrentarte a proyectos o librerías que usen JQuery como Bootstrap.

Te dejo un recurso esencial para ver como es usar [Jquery vs JS](http://youmightnotneedjquery.com/), pero esto también lo veremos en clase en unos días...
