### ISSUE TITLE
Dejando un legado de issues para futuros masters de fictizia

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#29]
Aahhh...¿qué sería de la vida si no pudiéramos aspirar a dejar un legado? Me preguntaba si es posible dejar issues para que todo lo que vamos aprendiendo sea heredado por quienes vengan después de nosotros.
Y si pudieran servir para la comunidad osw, ya sería la repera...
Cómo alguien dijo:

> Nuestro techo, será el suelo de nuestros hijos

**Comment by JGuijarro** [comment]
Que sufran, como hemos sufrido nosotros.
(Si no te salen hijos malcriados :stuck_out_tongue: )
