### ISSUE TITLE
Usuarios de Slack!

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#3]
Espero que ya estéis todos en Slack.. estoy creando un pequeño canal privado ^^

¿Que usuarios tenéis? (No usar la `@` para no mencionar a gente de github ajena en este issue)

Si no tienes usuario... [Date de Alta](https://slack.osweekends.com)

**Comment by Fa-v** [comment]
Hola, Mi usuario es fabiola

**Comment by KoolTheba** [comment]
Yo sólo os he podido añadir a tí @UlisesGascon y @Fa-v a mi repo! :(

**Comment by KoolTheba** [comment]
Y a JOrge

**Comment by UlisesGascon** [comment]
@KoolTheba que repo? :-)
