### ISSUE TITLE
¿Qué son y para que sirven las funciones anónimas?

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#31]
Quiero meterlas en mi primer proyecto como parte de los objetivos secundarios. He leído algún libro de javascript pero no me entereao muy bien de para qué son y para qué sirven.

**Comment by GuillermoBaldan** [comment]
No sé como se puede invocar una función anónima ni que ventajas le daría a mi proyecto el uso de estas.

**Comment by GuillermoBaldan** [comment]
He publicado una [pregunta en stackoverflow sobre esto](https://es.stackoverflow.com/questions/204095/ejercicio-sencillo-para-entender-la-utilidad-de-las-funciones-an%C3%B3nimas?noredirect=1#comment381612_204095).

**Comment by UlisesGascon** [comment]
En 5 clases lo vemos al detalle, pero sin uno de los recursos más potentes que tenemos enJavaScript.
