### ISSUE TITLE
¿Qué relación tienen las funciones autoejecutadas y las funciones anónimas?

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#32]
¿Qué puedo decir a estas alturas? Me lo paso pipa abriendo issues, contestándomelos yo mismo y cerrándolos...Me gusta buscar la verdad a través del diálogo como hacían los filósofos griegos. ¿Qué nadie dialoga conmigo? no pasa naaa... dialogo yo conmigo mismo...:stuck_out_tongue_winking_eye:
Por cierto, tranquilo profe, que no cunda el pánico que pienso ir cerrando issues...pero poco a poco según vaya recibiendo iluminación.

A ver...funciones autoejecutadas y funciones anónimas.
¿Todas las funciones autoejecutadas son funciones anónimas y viceversa?
Bueno, supongo que lo más natural para responder a esta pregunta, será preguntarme primero qué son las funciones autoejecutadas.

¿Qué a que viene mi interés por esto? Pues como objetivos secundarios del proyecto hay que meter funciones autoejecutadas.
Si no lo consigo ver con claridad en los próximos 15 minutos os prometo un issue dedicado a contestar que son las funciones autoejecutadas.

**Comment by UlisesGascon** [comment]
Creo que @Fa-v ya lo resuelve en el #33 :-)
