### ISSUE TITLE
¿Qué son y para que sirven las funciones autoejecutadas?

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#33]
Cómo no he conseguido contestarme a esta pregunta googleando en 15' pues creo que la pregunta merece una issue. Es que esto del desarrollo sea en el lenguaje que sea debería ser más como matrix, en el sentido en que la información debería absorberse rápidamente. La sensación que me da, es que en Internet la mayoría del mundo no sabe realmente nada, ya que me meto en sus webs, me leo lo que ponen y sigo sin enterarme.
Pues vamos al caso:
¿Qué son y para que sirven las funciones autoejecutadas? ¿Qué problema resuelven? ¿Realmente hacen nuestra vida más fácil?

**Comment by Fa-v** [comment]
Hola Guillermo,

Intentaré explicar, a ver que tal me va.

Las funciones que tienen nombre (function declarations, named functions) se invocan usando ese nombre:

```JavaScript
fucntion myFunction(a, b) {
  return a + b
};

myFunction(2,3);

```

Las funciones anónimas (function expressions) no llevan nombre:

```javascript
function (a, b) {
  return a + b
};
```

Este tipo de funciones pueden ser asignadas a una variable y las invocas usando la variable:

```javascript
var sum = function (a, b) {
  return a + b
};

var total = sum(5, 4)
```
O pueden pasarse como parámetro a otras funciones, por ejemplo dentro de un map:

```javascript
var numbers = [0, 1, 2];

var numbersPlusOne = numbers.map(function(number) {
  return number + 1;
});

// numbersPlusOne => [1,2,3];

```

En este caso podrías asignar a una variable la función que está dentro del map:

```javascript
var numbers = [0, 1, 2];
var addOne = function(number) {
  return number + 1;
};

var numbersPlusOne = numbers.map(addOne);

// numbersPlusOne => [1,2,3];

```

Usando Es6 puedes escribir lo mismo así:

```javascript
const numbers = [0, 1, 2];
const addOne = number => number + 1;

const numbersPlusOne = numbers.map(addOne);

// numbersPlusOne => [1,2,3];

```

Las funciones autoejecutadas (Inmediately Invoked Funcion Expressions, IIFE) son funciones que se llaman inmediatamente después de que la función es compilada por el navegador. Obtienes el resultado inmediatamente:

```javascript
var mensajeInmediato = (function() {
  console.log("Me ejecuto inmediatamente")
}());

(function(a,b) {
  console.log(a, b)
}("hola", "mundo"));

```
Cuando se compila el código JavaScript, el navegdaor lee primero las variables y digamos que las "eleva a un primer plano", eso se llama hoisting.

Las funciones autoinvocadas pueden ayudar a evitar que las variables sean "elevadas" a un contexto global y a la vez permite acceso público a los métodos que se exponen, manteniendo el contexto para cada variable definida dentro de la función.

Seguro que Ulises nos dará una mejor explicación de todo esto 😃

**Comment by UlisesGascon** [comment]
Gran explicación @Fa-v! :-)
