### ISSUE TITLE
Instalar Git desde npm

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#39]
¿Alguien sabe cómo instalar Git desde npm? He ido a la página de npm, he puesto "Git"  y me salen varias cosas y aunque están relacionadas con Git no parecen ser Git en si mismo. [La primera que sale](https://www.npmjs.com/package/git) por ejemplo, parece relacionar Git con Node, pero supongo que lo que estoy buscando es otra cosa, yo estoy buscando la herramienta en si misma, no cosas como interfaces.

**Comment by UlisesGascon** [comment]
Git no se instala desde NPM... todo lo que veas en NPM sobre GIT son librrías para trabajar con sus APIs. [Pasos para instalar GIT](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
