### ISSUE TITLE
Una pizarra...hmmm  😍

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#4]
Estaría bien tener una pizarra en clase, ¿he?
Estoy haciendo los deberes del conversor de números arábigos a números romanos y me estoy visualizando explicandolo en clase a través de una pizarra 😍

**Comment by UlisesGascon** [comment]
Tenemos las tabletas de dibujo y podemos proyectar tu pantalla directamente en la tele gigante ^^

El proximo día lo vemos en clase 👍
