### ISSUE TITLE
Kedada este viernes a las 17:00 en fictizia

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#41]
No hay nada como programar y hacerlo en compañía. Creo que podríamos quedar los que queramos este viernes a las 17:00 en fictizia (espero que no haya ningún problema). Para ir avanzando en nuestros proyectos. Lo que no se le ocurra a uno se le ocurrirá a otro...Seguro que aprendemos los unos de los otros.
Será interesante. De entrada, Jorge y yo vamos a quedar.
Hacemos esta kedada extensiva al resto.
Nos vemos!
![high-five1](https://user-images.githubusercontent.com/43887483/47000655-03a7e800-d129-11e8-8a88-4ee063908e5b.gif)

**Comment by UlisesGascon** [comment]
Por Fictizia... ningún problema ;-)

**Comment by qlchose** [comment]
Ánimo!! Saldo a las 18 :(

**Comment by Fa-v** [comment]
Ahí nos vemos!
