### ISSUE TITLE
¿Cómo crear un archivo con javascript?

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#48]
Hola, me gustaría generar un .txt que guardara unos strings. ¿Cómo puedo hacerlo?
Creo que sería una función, a la cual, le pasara el texto que quiero guardar y la ruta donde quiero guardarlo.

**Comment by GuillermoBaldan** [comment]
He encontrado el siguiente código en stackoverflow:

```javascript
var saveData = (function () {
    var a = document.createElement("a"); //¿Por qué tenermos que escribir entre paréntesis "a"?
    document.body.appendChild(a);
    a.style = "display: none"; // ¿Qué es style?
    return function () {
        var blob = new File(["HOLA Mundo!"], "holamundo.txt");
            url = window.URL.createObjectURL(blob);
        console.log(url);
        a.href = url;
        a.download = blob.name; //¿Qué guarda a.download?
        a.click(); //¿Qué significa esto?
        window.URL.revokeObjectURL(url);
    };
}());
```
Pero cómo indico en los comentarios hay cosas que no entiendo. Además me gustaría poder controlar en que ruta guardo mi archivo para poder seleccionar otra que sea diferente a la de la carpeta download que es donde por defecto te lo guarda esta función.

**Comment by Fa-v** [comment]
`document.createElement()` [es un método que crea las etiquetas de HTML](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement). Poniendo "a" entre los paréntesis le estás diciendo al método que cree una etiqueta [anchor de HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) `<a href=""></a>`.

`style` se refiere a los estilos de CSS que vas a dar al elemento que estás creando (color, tipografía, tamaño de la tipografía, etc), en este caso [a.style = "display: none";](https://www.w3schools.com/cssref/pr_class_display.asp) está diciendo que el elemento <a> [no se va a mostrar en el DOM](https://www.w3schools.com/cssref/playit.asp?filename=playcss_display&preval=none).

`a.click();` Está agregando el evento click al <a> para que cuando se muestre el usuario pueda clicar en él, es este momento ese evento no hace nada, falta pasarle la función que le diga qué hacer, algo así:
```javascript
a.addEventListener('click', function () {
    a.style.display = 'block';
  });
```
Aquí primero estas [agregando el evento](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) click al <a> con el método `addEventListener`, luego, dentro de la función le estás diciendo que te mueste el elemento.

Espero que esto te ayude 😄

**Comment by GuillermoBaldan** [comment]
¡Muchísimas gracias! Te lo has currado. Ahora me queda más claro.

**Comment by GuillermoBaldan** [comment]
Creo que este código es más fácil de entender para mí:
```javascript
function saveTextAsFile()
{      
// grab the content of the form field and place it into a variable
    var textToWrite = document.getElementById("inputTextToSave").value;
//  create a new Blob (html5 magic) that conatins the data from your form feild
    var textFileAsBlob = new Blob([textToWrite], {type:'text/plain'});
// Specify the name of the file to be saved
    var fileNameToSaveAs = "myNewFile.txt";
    
// Optionally allow the user to choose a file name by providing 
// an imput field in the HTML and using the collected data here
// var fileNameToSaveAs = txtFileName.text;
 
// create a link for our script to 'click'
    var downloadLink = document.createElement("a");
//  supply the name of the file (from the var above).
// you could create the name here but using a var
// allows more flexability later.
    downloadLink.download = fileNameToSaveAs;
// provide text for the link. This will be hidden so you
// can actually use anything you want.
    downloadLink.innerHTML = "My Hidden Link";
    
// allow our code to work in webkit & Gecko based browsers
// without the need for a if / else block.
    window.URL = window.URL || window.webkitURL;
          
// Create the link Object.
    downloadLink.href = window.URL.createObjectURL(textFileAsBlob);
// when link is clicked call a function to remove it from
// the DOM in case user wants to save a second file.
    downloadLink.onclick = destroyClickedElement;
// make sure the link is hidden.
    downloadLink.style.display = "none";
// add the link to the DOM
    document.body.appendChild(downloadLink);
    
// click the new link
    downloadLink.click();
}
 
function destroyClickedElement(event)
{
// remove the link from the DOM
    document.body.removeChild(event.target);
}
 
// EOF
```
