### ISSUE TITLE
¿Qué opináis sobre el libro "JavaScript Cookbook?

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#49]
Estoy pensando en comprármelo: [JavaScript Cookbook](http://shop.oreilly.com/product/9780596806149.do)

**Comment by qlchose** [comment]
umm ... Google es tu amigo

**Comment by UlisesGascon** [comment]
De entrada te diría que tienes alternativas mejores entre los libros que [os recomendé](https://github.com/Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3/blob/master/teoria/clase1.md#libros), por otro lado el autor es muy bueno :-) 

Pero el libro es de 2010... lo que hace que sea muy anterior a grandes cambios que hoy en dia son básicos conocer como ES6 y arquitecturas sin JQuery, etc...
