### ISSUE TITLE
Creando una interfaz gráfica para un explorador de archivos

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#51]
La verdad, es que siempre he querido hacer un explorador de archivos que organizara mis archivos por tags. He empezado a montarme uno, de momento me funciona a nivel de consola, pero me gustaría tener una interface gráfica y que pudieras interaccionar con la información a través del ratón. Al principio pensé en usar etiquetas para mostrar la información, pero debido a la naturaleza dinámica de esta, no puedo representar una información que va aumentando con una cantidad estática de etiquetas. Entonces he pensando en usar el Canvas, pero no sé si este me permite generar imágenes con las que pueda interactuar mediante ratón. ¿Alguien me recomienda algo?
Por si no se me entiende bien, ahí va un pantallazo de algo que se parece visualmente a lo que quiero hacer. Tengo que dibujar carpetas y tags.
![pantallazo explorer](https://user-images.githubusercontent.com/43887483/47171628-7a034080-d309-11e8-8197-1ef0c45beb47.png)

**Comment by GuillermoBaldan** [comment]
Por si alguien quiere participar. [He publicado una pregunta parecida a estas en stackoverflow](https://es.stackoverflow.com/questions/205852/creando-una-interfaz-gr%C3%A1fica-para-hacer-un-explorador-de-archivos)

**Comment by UlisesGascon** [comment]
De entrada yo creo que tendrías que apoyarte mucho en los metadatos que se asocian a los ficheros. Con eso podrías crear un campo personalizado que luego puedas utilizar para etiquetar los ficheros.

El problema de base es que los exploradores de ficheros no reconocerán ese campo y tendrás que hacer tu también el explorador... que se podría hacer con Node + WS + Front... pero arquitecturalmente es un proyecto grande y complejo.

**Comment by UlisesGascon** [comment]
https://lucene.apache.org/core/

**Comment by UlisesGascon** [comment]
### Esquemas
```
/assets
    /jquery.js
/index.html
/style.css
```

```js
var ficheros = {
    "assets": {
        isFolder: true,
        tags: ["web", "assets"],
        files: {
            "jquery.js": {
                isFile: true,
                tags: ["web", "jquery"]
            }
        }
        
    },
    "index.html": {
        isFile: true,
        tags: ["web", "html"]
    },
    "style.css": {
        isFile: true,
        tags: ["web", "css"]
    }
    
}    
```
### Recursos
- https://bootsnipp.com/snippets/orZlP
- https://codepen.io/enahom99/pen/MazNRV
- https://editor.datatables.net/
