### ISSUE TITLE
Error Generando etiquetas dinámicamente

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#53]
Hola, tengo el siguiente fragmento de código:
```javascript
var labelArray = [];
function createlabel(){
 labelArray.push(document.createElement("h1"));
 document.body.appendChild(labelArray[-1]);
 labelArray[-1].style = "color: blue";
 labelArray[-1].value = "etiqueta de ejemplo";
}
createlabel();
```
Al ejecutarlo, me da un error:

> Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

Me da ese error en la sentencia: `document.body.appendChild(labelArray[-1]);`
¿Alguien sabe que significa y cómo puedo solventarlo?

**Comment by UlisesGascon** [comment]
No entiendo que queires hacer... `-1`?
