### ISSUE TITLE
Proyecto 23N. APP de microcursos

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#6]
Hola Ulises! Me estoy poniendo con el proyecto que tenemos que entregar el 23  de noviembre.
Ya te comenté la idea de hacer una aplicación de cursos como la de Sololearn.
Veo que para este proyecto puedo hacer dos cosas:
- Una web de consulta de cursos online disponibles: escribes una descripción de una línea de tu curso y te busca en las webs de coursera, udacity, edx y miriadax.

- Una web de consulta de datos de usuario: Usando faker.js hacemos montañas de datos falsos de usurios para simular la base de datos que en un futuro tendré de los usuarios que estén inscritos en en mi web. La idea sería que introduciendo el nombre de usario o el email me dieran los datos asociados a ese usuario. Los datos asociados a ese usuario podrían ser: email, nombre de usuario, foto de perfil (aquí podriamos generar un mapa de bits aleatorio para cada usuario), cursos inscritos, y progreso en cada curso (un número entre 0 y 100)

Yo prefiero hacer la segunda opción por ir manejando los datos de usuario y así de paso preparo la base de datos mi web.
Tendríamos que crear una base de datos y una api que permitiera consultas a esa base de datos, ¿no?

Bueno, pues quedo a la espera de que me comentes por donde puedo tirar y si algunos queréis darme alguna idea pues os estaría agradecido hasta el punto de invitaros a unas cañas o a unos cafes, lo que prefirais...además os haría descuentos muy sustanciosos en mis cursos (que ya de por sí van a ser baratos) :laughing:

**Comment by GuillermoBaldan** [comment]
A ver he hecho un espacio de trabajo en el cloud9, he seleccionado el template de Node.js para mi proyecto empresarial.
No hay template para hacer cosas con angular?
Lo he puesto como privado, ¿cómo puedo hacer que tú, Ulises, puedas acceder?

**Comment by UlisesGascon** [comment]
Genial! Mañana en clase vemos como compartirnos los workspaces :-) 

El proyecto tiene muy buena pinta! Si quieres hacemos juntos un Roadmap de todo tu proyecto empresarial y lo encajamos segun el tramo del master en el que estemos y asi tienes los tres proyectos personales cubiertos y llegas sin problemas a las fechas de entregas ;-)

**Comment by GuillermoBaldan** [comment]
Oh! Eso estaría muy bien! Pues dime cuando te viene bien que hagamos el Roadmap.

**Comment by UlisesGascon** [comment]
### Notas

- Vistas
	- Home -> /
	- 404 -> /*
	- Catalogo -> /catalogo -> https://platzi.com/
	- Detalle_curso -> /curso/:id -> https://platzi.com/cursos/git-github/


- AJAX?
	- /data/api_catalogo.json -> `[{...}, {...}]`
	- /data/api_curso.json -> 
	```
	{
		nombre_curso: "",
		descripcion: "",
		foto: "",
		...
	}
	```
### Recursos

- [faker.js](https://github.com/marak/Faker.js/)
- [json-generator](https://www.json-generator.com/)
- [Hyper – Responsive Admin & Dashboard Template](https://themes.getbootstrap.com/product/hyper-responsive-admin-dashboard-template/)
- [krasimir/navigo](https://github.com/krasimir/navigo)
