### ISSUE TITLE
Refrescando el datatable de mi "Explorador de archivos"

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#60]
Consigo visualizar datos, pero al añadir nuevos datos no consigo verlos. He hecho una función que se supone que tenía que repintarme la tabla que uso para ver mis datos pero nada.
De momento he llegado hasta aquí.
![editor de archivos](https://user-images.githubusercontent.com/43887483/47255291-f7949100-d46e-11e8-808f-9bb49b720b5f.png)
Tengo estas líneas de código en .js que son las que me hacen el trabajo de dibujar la tabla, al menos eso es lo que entiendo yo:
```javascript
$(document).ready(function() {
    $('#example').DataTable( {
        data: dataSet, 
        columns: [
            { title: "FileName" },
            { title: "Tags" },
                 ]
    } );
} );
```
Lo encapsulo dentro de una función a la que llamo `drawData` quedando esto así:
```javascript
function drawData(){
$(document).ready(function() {
    $('#example').DataTable( {
        data: dataSet, 
        columns: [
            { title: "FileName" },
            { title: "Tags" },
                 ]
    } );
} );
}
```
Luego voy metiendo datos a un array de objetos, los paso por una función que los convierte a `dataSet`, que es otro array, pero no de objetos y llamo desde la consola a  la función `drawData` pero no me aparece actualizada la tabla con los nuevos datos. Si antes de usar `drawData `meto varios datos y luego llamo a `drawData`, si me aparecen todos los datos, pero si meto después nuevos datos y llamo a la función `drawData` no se me actualiza la tabla.
¿Alguién tiene alguna idea de que puede estar sucediendo y como solventar este problema?
Muchas gracias compañeros.

**Comment by UlisesGascon** [comment]
Grandes avances @GuillermoBaldan!! 

Creo que puedo ayudarte... en principio tu función `drawData` esta registrando un evento que ya no volverá a suceder (que el documento este listo de nuevo). 

Asi que un hack rápido a la pelicula sería este...

```js
//Tu función sin eventos...
function drawData(){
    $('#example').DataTable( {
        data: dataSet, 
        columns: [
            { title: "FileName" },
            { title: "Tags" },
                 ]
    } );
}



// Al iniciar la APP
$(document).ready(drawData)


//Cada vez que quieras refrescar...
drawData()
```

**Comment by GuillermoBaldan** [comment]
Ok! Perfecto. Lo voy a probar...

**Comment by GuillermoBaldan** [comment]
Al final me resulta práctica tu respuesta combinada con [esta otra](https://es.stackoverflow.com/questions/206331/visualizando-propiedades-de-archivos-con-una-tabla-de-datos/206341#206341).  Por lo visto al trabajar con dataTable no se puede volver a llamar la misma funcion si ya ha sido ha llamada, puesto que esta no se puede reiniciar, lo que me sugieren es que destruya la función con este metodo `$("#example").dataTable().fnDestroy();` y volver a ponerla.
Me dan  [esta referencia](http://vertutoriales.com/reiniciar-datatable-cannot-reinitialise-datatable/).

**Comment by GuillermoBaldan** [comment]
Finalmente, lo que he hecho ha sido crear dos funciones:
drawData() y reDrawData().  La primera la uso una vez, al cargar la página por primera vez. Mientras que la segunda la uso siempre que quiero refrescar la tabla. De esa forma, no me salta ningún error.
```javascript
function drawData(){
    $('#example').DataTable( {
        data: dataSet, 
        columns: [
            { title: "FileName" },
            { title: "Tags" },
                 ]
        } );
            
}


function reDrawData(){
    $("#example").dataTable().fnDestroy();
    $('#example').DataTable( {
        data: dataSet, 
        columns: [
            { title: "FileName" },
            { title: "Tags" },
                 ]
        } );

}
```

**Comment by UlisesGascon** [comment]
Si finalmente utilizas AJAX para traer los datos... podrías usar `ajax.reload()`, [doc](https://datatables.net/reference/api/ajax.reload()) y sería una solución más elegante ;-)
