### ISSUE TITLE
Software de animaciones sobre la evolución de un proyecto

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#7]
¿Alguien sabe que software hace estas animaciones chulísimas sobre la evolución de un proyecto?
Aquí tenéis un ejemplo: [Evolution of faker.js](https://www.youtube.com/watch?v=hGD4MOcCN94)
La verdad es que no es la primera vez que veo estas animaciones y siempre me quedo con ganas de saber que software es.

**Comment by UlisesGascon** [comment]
Creo que usan [gource](https://gource.io/), lo mas parecido en NPM que he visto es [este proyecto de visualización](https://www.npmjs.com/package/wiki-evolution) que lo usa.
