### ISSUE TITLE
Trabajando con una plantilla de Bootstrap y gulp - Problemas para visualizar correctamente una página

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#70]
Hay una página en mi plantilla de Bootstrap llamada "pages-starter.html" y no consigo el resultado esperado (ver imagen de "starter page.png"). Lo que obtengo es una página del aspecto que puede verse en la imagen "My starter page.png" No entiendo los siguientes textos que pueden verse en dicha página:
```
@@include("file:///C:/Users/USER/Google Drive/Gproyectos/APP Microcourses/Vistas.Bootstrap.Hyper.P23N/src/html/partials/left-sidebar.html")
@@include('./partials/topbar.html')
@@include('./partials/footer.html')
@@include('./partials/right-sidebar.html')
```
Por cierto, creo que se supone que he de usar gulp.
![my starter page](https://user-images.githubusercontent.com/43887483/47386983-5deb0f00-d70e-11e8-875b-cb42c0e9214d.png)
![starter page](https://user-images.githubusercontent.com/43887483/47386984-5deb0f00-d70e-11e8-8163-4b8d607c8281.png)

**Comment by UlisesGascon** [comment]
mñn vemos la estructura que tiene el proyecto y te confirmo que le pasa.. pero sin duda parece algo de automatización que no esta funcionando
