### ISSUE TITLE
Añadiendo una propiedad a un objeto en una función

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#71]
Tengo un objeto, más o menos grande:
```javascript
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
```
y quiero añadir la propiedad "artist" al album de ABBA Gold cuyo id es 5439.
Para ello hago una función:
```javascript
function updateRecords(id, prop, value) {
     collection[id].prop = value;
     return collection;
}
```
resulta que cuando en mi programa yo escribo:
`updateRecords("5439","artist","ABBA");` me lo actualiza mal, porque si escribo `collection[5439]` el objeto que me arroja es este:
{album: "ABBA Gold", prop: "ABBA"}
 Cómo veis no tiene la propiedad de "artist", sino la propiedad "prop". Eso es porque en la función en vez de coger la palabra "prop" (que en este caso es "artist") y ponerla como propiedad de un objeto, me pone como por defecto "prop" como propiedad. No le está dando el mismo tratamiento al prop que viene en la declaración de la función que al prop que viene en la sentencia collection[id].prop = value;
¿Cómo puedo corregir para que me aparezca como propiedad "artista"?

**Comment by UlisesGascon** [comment]
Tienes una errata...
```js
function updateRecords(id, prop, value) {
     collection[id][prop] = value;
     // La gestión de prop estaba mal...
     //collection[id].prop = value;
     // No necesitas retornar...
     //return collection;
}
```
