### ISSUE TITLE
Añadiendo una organización a mi perfil de GitHub

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#72]
Tengo dos organizaciones en mi "Profile". Me gustaría añadir la de Freecodecamp. ¿Cómo podría hacerlo? Me voy a la sección de "Organizations" le doy al botón de "New organization" y me dice "Create an organization account" pero yo no quiero hacer eso. Yo solo quiero vincular Freecodecamp a mi "Profile" como organización de la que soy parte.

**Comment by UlisesGascon** [comment]
Tienen que invitarte ellos a ti ;-)
