### ISSUE TITLE
Resumen de Object.freeze para Eva

### ISSUE THREAD

**Issue by JGuijarro** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#79]
![221600x435](https://user-images.githubusercontent.com/43820446/47585218-ee1e9380-d95c-11e8-8e61-23a77741955c.jpg)

**Comment by qlchose** [comment]
Gracias!!

**Comment by GuillermoBaldan** [comment]
Bueno, me parece interesante conocer ese método, aunque no sirva para mucho...

**Comment by UlisesGascon** [comment]
hahahahahahahahaha
![lol-meme](https://user-images.githubusercontent.com/5110813/47663353-1268b300-db9d-11e8-9c24-12af4e076049.jpg)
