### ISSUE TITLE
¿Cómo instalar librerías en un área de trabajo de Cloud9?

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#8]
Hola! Quiero instalarme faker.js para generar perfiles que simulen usuarios de mi app, pero me doy cuenta que en mi área de trabajo de Cloud9 que es un template de Node no reconoce las sentencias de código que hacen referencia a la librería faker.js. Entonces supongo que tengo que instalar faker.js en mi máquina de cloud9. ¿Alguien sabe cómo puedo hacer esto?

**Comment by UlisesGascon** [comment]
Sip... tienes dos formas fundamentales de hacerlo si no te sales de JS y Node. 

Si haces solo front, solo necesitas importarte las librerías con la etiqueta `<script>`. [Guía](https://www.w3schools.com/tags/att_script_src.asp)

Si estas usando backend, tienes que usar NPM. [Guía](https://docs.npmjs.com/getting-started/installing-npm-packages-locally)

Si quieres hacer otras cosas o usar otras librerías, básicamente c9 por debajo en Ubuntu con lo que solo necesitas hacer los típicos comandos...
`sudo apt-get install loque-sea`, etc...

**Comment by UlisesGascon** [comment]
Lo vemos ahora en clase ^^
