### ISSUE TITLE
Requisito llamada AJAX ¿A dónde llamo?

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#85]
Hola Ulises, como uno de los requisitos que tiene que tener el proyecto a entregar, dices que hay que hacer una llamada AJAX. ¿A dónde puedo llamar? Si tuviera una base de datos, supongo que podría llamar a la base de datos, pero como no hemos llegado a esa parte del temario...

**Comment by UlisesGascon** [comment]
En principio tenemos 3 opciones de cara al proyecto.
1. Tener una API pública disponible, tipo Open Weather Map... (No es tu caso)
2. Tener un backend y su API (No es tu caso aún ;-))
3. Generarte un fichero json y hacer una llamada contra él, que sería lo que te recomiendo en tu caso.
