### ISSUE TITLE
Funcionamiento array.sort()

### ISSUE THREAD

**Issue by qlchose** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#86]
Hola, 

Por favor, tengo estas dudas:

¿Cómo conseguir que sort() organice los elementos de tipo texto de un array por tamaño (length)?
Cuando ordena por texto ¿cuál es el criterio que utiliza? Es decir, ¿UTF-8?¿se le puede indicar que incluya otra ordenación alfabética?.

Gracias !!

**Comment by Fa-v** [comment]
Hola Eva,

Según [MDN el método sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) usa "The ... string Unicode code points.".

Si quieres hacer un sort de un array de strings que tienen letras mayúsculas y minúsculas, debes primero convertir los strings a lowerCase y luego hacer el sort.

```js
var frutas = ['papaya', 'Sandia', 'guanabana', 'aguacate'];

var sortFrutas = frutas
  .map(function(fruit) {
    return fruit.toLowerCase();
  })
  .sort(function(str1, str2) {
    return str1.length > str2.length;
  });

console.log(sortFrutas); //Ordenadas por el length del string [ 'papaya', 'sandia', 'aguacate', 'guanabana' ]

var sortFrutas = frutas
  .map(function(fruit) {
    return fruit.toLowerCase();
  })
  .sort(function(str1, str2) {
    return str1 > str2;
  });

console.log(sortFrutas); //Ordenadas alfabéticamente [ 'aguacate', 'guanabana', 'papaya', 'sandia' ]
```

Espero que esto ayude a resolver tu duda.

**Comment by GuillermoBaldan** [comment]
¡Qué máquina estas hecha Fabiola!

**Comment by UlisesGascon** [comment]
+1 Genial explicación @Fa-v !!
