### ISSUE TITLE
Ejercicios completos

### ISSUE THREAD

**Issue by karinagdavila** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#92]
Clase 2: https://gist.github.com/karinagdavila/9b8a0d6f6ada7bfbfb7639ba06aabdfc

https://github.com/Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3/blob/master/Karina/doc.md

**Comment by UlisesGascon** [comment]
Gracias @karinagdavila !!
