### ISSUE TITLE
Haciendo un juego de estrategia en 2D de cero jugadores

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#96]
A veces antes de ponerme con los deberes del máster o con el proyecto siempre trato de dedicar un ratito a un proyecto que me guste, vamos... por puro placer.
Hacia tiempo que quería hacer un juego de estrategia tipo age of empires pero para no complicarme mucho la vida con la parte gráfica quería usar solo gráficos en 2D. había pensado en representar las cosas por cuadraditos. También he de aclarar que sería de cero jugadores. La dinámica de juego consiste en definir las reglas que rigen una población que tu eliges y le das al play y ves como eso va evolucionando y si consigue sobrevivir o conquistar a las poblaciones que están presentes en el escenario. He pensado en usar el canvas, no sé que otras opciones tengo de dibujo...¿Qué herramientas me recomendaís para pintar la información?

**Comment by UlisesGascon** [comment]
@GuillermoBaldan, te paso algunos recurso que igual te ayudan :-)
- [MDN | Famoso juego 2D usando JavaScript puro](https://developer.mozilla.org/es/docs/Games/Workflows/Famoso_juego_2D_usando_JavaScript_puro)
- [Github | JavaScript Game Engines](https://github.com/collections/javascript-game-engines)
- [phaser.io](https://phaser.io/learn)
