### ISSUE TITLE
¿Se pueden presentar varios proyectos?

### ISSUE THREAD

**Issue by GuillermoBaldan** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#99]
De cara a a la presentación del 15 de Enero, ¿podría presentar varios proyectos?
Es que tengo el de la plataforma de cursos, luego tengo el ZeroPlayers (juego de estrategia de cero jugadores -[ ver repo](https://github.com/GuillermoBaldan/ZeroPlayers)) y luego tengo uno llamado "Charts for daily progress" que va sobre visualizar datos de productividad diario (básicamente tiempos de tareas y proyectos). Creo que podría contribuir a que la presentación fuese más enriquecedora.

**Comment by UlisesGascon** [comment]
Los que quieras ^^
